
" Spacing
set tabstop=4
set softtabstop=0
set shiftwidth=4
set expandtab

" Style
syntax on
set number

" Templates by extension
if has("autocmd")
  augroup templates
    autocmd BufNewFile *.pl 0r ~/.vim/templates/skeleton.pl
  augroup END
endif

" Functions
function! ModSubName() abort
    let module_name = search('^package ', 'cnw')
    let prev_sub_line_num = search('^sub ', 'bcnW')
    return matchstr(getline(module_name), 'package \zs[^; ]\+') . '::' . matchstr(getline(prev_sub_line_num), 'sub \zs\w\+')
endfunction
